import Testing
@testable import GlyphlineCore

/// A real SCC file generated by pycaption (an independent, widely-used
/// implementation) from a two-caption SRT, then verified by feeding it back
/// through ffmpeg's independent `eia_608` decoder and confirming the decoded
/// text/rough timing matched — see the task notes for the exact commands.
/// Two unrelated implementations agreeing is the strongest correctness check
/// available here (there's no live spec doc to check against in this
/// environment), and it caught real issues in a sibling format's first draft
/// (see STLTests.swift), which is exactly why this exists for SCC too.
private let referenceSCC = """
Scenarist_SCC V1.0

00:00:00:13\t94ae 94ae 9420 9420 94e0 94e0 c8e5 ecec ef20 f7ef f2ec 6480 942c 942c 942f 942f

00:00:02:29\t942c 942c

00:00:04:01\t94ae 94ae 9420 9420 9440 9440 d3e5 e3ef 6e64 20ec e96e e520 ef6e e580 94e0 94e0 d3e5 e3ef 6e64 20ec e96e e520 f4f7 ef80 942c 942c 942f 942f

00:00:07:14\t942c 942c
"""

@Suite("SCC: golden reference (pycaption-generated, ffmpeg-verified)")
struct SCCGoldenReferenceTests {
    @Test("parses two cues with the expected text")
    func parsesText() {
        let doc = parseScc(referenceSCC)
        #expect(doc.cues.count == 2)
        #expect(doc.cues[0].text == "Hello world")
        #expect(doc.cues[1].text == "Second line one\nSecond line two")
    }

    @Test("parses cue start from the EOC event and end from the next EDM")
    func parsesTiming() {
        let doc = parseScc(referenceSCC)
        // NDF timecode math: the frame field counts at the NOMINAL rate (30),
        // then the total is divided by the TRUE rate (29.97…) — matching
        // FrameTime.swift's parseFrameTimecode, not a naive seconds+frames/fps
        // sum (those two formulas diverge exactly because fps != round(fps)).
        func expected(_ h: Int, _ m: Int, _ s: Int, _ f: Int) -> Double {
            Double((h * 3600 + m * 60 + s) * 30 + f) / SCCTestFPS
        }
        #expect(abs(doc.cues[0].start - expected(0, 0, 0, 13)) < 1e-9)
        #expect(abs(doc.cues[0].end - expected(0, 0, 2, 29)) < 1e-9)
        #expect(abs(doc.cues[1].start - expected(0, 0, 4, 1)) < 1e-9)
        #expect(abs(doc.cues[1].end - expected(0, 0, 7, 14)) < 1e-9)
    }

    @Test("sets the frame rate to the line-21 standard 29.97")
    func parsesFrameRate() {
        #expect(parseScc(referenceSCC).frameRate == SCCTestFPS)
    }
}

private let SCCTestFPS = 30000.0 / 1001.0

@Suite("SCC: round trip")
struct SCCRoundTripTests {
    @Test("plain text round-trips through parse(serialize())")
    func plainText() {
        var doc = SubtitleDocument(format: .scc)
        doc.cues = [
            Cue(id: "a", start: 1, end: 3, text: "Hello world"),
            Cue(id: "b", start: 5, end: 7, text: "Second line one\nSecond line two"),
        ]
        let out = parseScc(serializeScc(doc))
        #expect(out.cues.map(\.text) == ["Hello world", "Second line one\nSecond line two"])
        #expect(abs(out.cues[0].start - 1) < 1.0 / SCCTestFPS)
        #expect(abs(out.cues[1].end - 7) < 1.0 / SCCTestFPS)
    }

    @Test("supported special Latin characters round-trip")
    func specialChars() {
        var doc = SubtitleDocument(format: .scc)
        doc.cues = [Cue(id: "a", start: 0, end: 2, text: "café con leche, ¿dónde está el niño?"
            .replacingOccurrences(of: "¿", with: "").replacingOccurrences(of: "?", with: ""))]
        // (¿/? aren't in the basic table's substitution set — keep this test
        // to the characters this adapter actually claims to support.)
        let out = parseScc(serializeScc(doc))
        #expect(out.cues[0].text == doc.cues[0].text)
    }

    @Test("an odd character count still round-trips (padding byte dropped on decode)")
    func oddLength() {
        var doc = SubtitleDocument(format: .scc)
        doc.cues = [Cue(id: "a", start: 0, end: 2, text: "odd")]
        let out = parseScc(serializeScc(doc))
        #expect(out.cues[0].text == "odd")
    }

    @Test("back-to-back cues don't get a redundant standalone erase between them")
    func backToBackNoRedundantErase() {
        var doc = SubtitleDocument(format: .scc)
        doc.cues = [
            Cue(id: "a", start: 0, end: 2, text: "one"),
            Cue(id: "b", start: 2, end: 4, text: "two"),
        ]
        let scc = serializeScc(doc)
        // Only 3 timecoded lines total: cue A's block, cue B's block, and B's
        // trailing erase — NOT a 4th redundant erase at t=2 between them.
        let timecodedLines = scc.split(separator: "\n").filter { $0.contains("\t") }
        #expect(timecodedLines.count == 3)
    }

    @Test("a gap between cues gets its own standalone erase")
    func gapGetsOwnErase() {
        var doc = SubtitleDocument(format: .scc)
        doc.cues = [
            Cue(id: "a", start: 0, end: 2, text: "one"),
            Cue(id: "b", start: 5, end: 7, text: "two"),
        ]
        let scc = serializeScc(doc)
        let timecodedLines = scc.split(separator: "\n").filter { $0.contains("\t") }
        #expect(timecodedLines.count == 4) // A's block, A's erase, B's block, B's erase
    }

    @Test("three text lines climb rows upward from the bottom-anchored row 15")
    func multiLineRows() {
        var doc = SubtitleDocument(format: .scc)
        doc.cues = [Cue(id: "a", start: 0, end: 2, text: "one\ntwo\nthree")]
        let out = parseScc(serializeScc(doc))
        #expect(out.cues[0].text == "one\ntwo\nthree")
    }

    @Test("cues serialize in time order regardless of input order")
    func sortsOnSerialize() {
        var doc = SubtitleDocument(format: .scc)
        doc.cues = [
            Cue(id: "b", start: 5, end: 6, text: "second"),
            Cue(id: "a", start: 1, end: 2, text: "first"),
        ]
        let out = parseScc(serializeScc(doc))
        #expect(out.cues.map(\.text) == ["first", "second"])
    }

    @Test("an empty document serializes to just the header")
    func emptyDocument() {
        let scc = serializeScc(SubtitleDocument(format: .scc))
        #expect(scc.contains("Scenarist_SCC V1.0"))
        #expect(!scc.contains("\t"))
    }
}

@Suite("SCC: parity")
struct SCCParityTests {
    @Test("every encoded byte has odd total 1-bit parity")
    func alwaysOddParity() {
        for raw: UInt8 in 0...0x7F {
            let encoded = sccParity(raw)
            #expect(encoded.nonzeroBitCount % 2 == 1)
        }
    }

    @Test("stripping parity recovers the original 7-bit value")
    func stripRecoversOriginal() {
        for raw: UInt8 in 0...0x7F {
            #expect(sccStripParity(sccParity(raw)) == raw)
        }
    }

    @Test("known control-code bytes match the verified reference values")
    func knownValues() {
        // From the golden SCC above: ENM=94ae, RCL=9420, EDM=942c, EOC=942f.
        #expect(sccParity(0x14) == 0x94)
        #expect(sccParity(0x2E) == 0xAE)
        #expect(sccParity(0x20) == 0x20)
        #expect(sccParity(0x2C) == 0x2C)
        #expect(sccParity(0x2F) == 0x2F)
    }
}
